name: charles_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  firebase_auth: ^0.18.0+1
#  firebase_core: ^0.5.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.13.1+1
#  cloud_firestore: ^0.14.0+2
  package_info: ^0.4.3
  device_info: ^0.4.2+8
  flutter_svg: 0.18.1
  table_calendar: ^2.3.0
  geocoder: ^0.2.1
  dio: 3.0.10
  flutter_staggered_grid_view: ^0.3.2
  datetime_picker_formfield: ^1.0.0
  getflutter: ^1.0.11
  google_maps_flutter: ^0.5.33
  awesome_card: ^1.1.0
  percent_indicator: ^2.1.7+4
  location: ^2.5.3
  tinycolor: ^1.0.2
  polygon_clipper: ^1.0.2
  flutter_masked_text: ^0.8.0
  image_picker: ^0.6.7+17
  simple_animations: ^2.4.2
  country_code_picker: ^1.6.0
  flutter_rating_bar: 3.0.1+1
  number_inc_dec: ^0.6.6
  animated_splash_screen: ^1.0.1+2
  circular_check_box: ^1.0.4
  dotted_line: ^2.0.2
  progress_dialog: ^1.2.4
  sizer: 1.1.7
  geolocator: ^6.1.13
  smooth_star_rating: 1.1.1
  fluttertoast: ^7.1.1
  delayed_display: ^1.0.3
  shared_preferences: ^0.5.12+4
  firebase_database:
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+1
  cloud_firestore: ^0.12.9+4
  day_night_time_picker: 0.5.0
  flutter_datetime_picker: ^1.4.0





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: monm
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: mmonb
      fonts:
          - asset: fonts/Montserrat-Bold.ttf
    - family: mmonm
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: mmonr
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: monr
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: monb
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: sour
      fonts:
        - asset: fonts/SourceSansPro-Regular.otf
    - family: soui
      fonts:
        - asset: fonts/SourceSansPro-It.otf
    - family: opsr
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: opsb
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
    - family: sspsb
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
    - family: rubik
      fonts:
        - asset: fonts/rubic.ttf
    - family: rubikl
      fonts:
        - asset: fonts/rubikL.ttf
    - family: rob
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
